[[index]]
name = "testpypi"
url = "https://test.pypi.org/legacy/"
publish-url = "https://test.pypi.org/legacy/"

[[index]]
name = "pypi"
url = "https://pypi.org/legacy/"
publish-url = "https://upload.pypi.org/legacy/"
